name: Nimble Agar Flake Steward

on:
  schedule:
    - cron: '45 7 * * 2'
  workflow_dispatch:

jobs:
  lockfile:
    strategy:
      matrix:
        repo:
          - armanbilge/fs2-dom
          - armanbilge/porcupine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: 206853
          private_key: ${{ secrets.NIMBLE_AGAR_STEWARD_PRIVATE_KEY }}

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v21
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: update/flake-lock
          git-author-email: 106723251+nimble-agar-steward[bot]@users.noreply.github.com
          git-author-name: nimble-agar-steward[bot]
          git-committer-email: 106723251+nimble-agar-steward[bot]@users.noreply.github.com
          git-committer-name: nimble-agar-steward[bot]
          pr-body: |
            Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
