name: Nimble Agar Steward

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

concurrency: steward

jobs:
  steward:
    runs-on: ubuntu-latest
    name: Nimble Agar Steward
    steps:
      - uses: sbt/setup-sbt@v1
    
      - uses: actions/checkout@v4
          
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: 206853
          private_key: ${{ secrets.NIMBLE_AGAR_STEWARD_PRIVATE_KEY }}

      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          author-email: 106723251+nimble-agar-steward[bot]@users.noreply.github.com
          author-name: nimble-agar-steward[bot]
          github-app-id: 206853
          github-app-key: ${{ secrets.NIMBLE_AGAR_STEWARD_PRIVATE_KEY }}
